platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

pod 'Moya/RxSwift', :path => "../"
pod 'Moya/ReactiveCocoa', :path => "../"
pod 'Moya', :path => "../"

target 'MoyaTests' do

 pod 'Quick', '~> 0.3.0'
 pod 'Nimble', '~> 0.4.0'
 pod 'OHHTTPStubs'

end
