disabled_rules:
  - line_length
  - type_name

opt_in_rules:
  - empty_count
  - force_unwrapping
  - extension_access_modifier

included:
  - Sources
  - Tests
  - Examples
  - Dangerfile.swift

function_body_length:
  warning: 50
