platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

pod 'ReactiveCocoa', '3.0-alpha.3'
pod 'Moya/Reactive', :path => "../"

target 'DemoTests' do

  pod 'Quick'
  pod 'Nimble'

end
