source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

# Our Libraries
def libraries
  pod 'Moya', :path => "../"
  pod 'Moya/ReactiveSwift', :path => "../"
  pod 'Moya/RxSwift', :path => "../"
  pod 'Alamofire', "~> 4.2.0"
  pod 'RxSwift'
  pod 'ReactiveSwift', '1.0.0-rc.3'
end

target 'Demo' do
  platform :ios, '8.0'
  libraries
end

target 'DemoMultiTarget' do
  platform :ios, '8.0'
  libraries
end
